import * as fs from 'fs';
import * as path from 'path';
import type { StackConfig } from '../config/stacks';

/**
 * Minimal generator for `stackspark new <project-name>`.
 * For now:
 *   - creates the target directory
 *   - creates empty frontend/ and backend/ directories
 *   - writes a simple README.md
 */
export async function generateProject(projectName: string, stack: StackConfig): Promise<void> {
    const targetRoot = path.resolve(process.cwd(), projectName);
  
    if (fs.existsSync(targetRoot)) {
      throw new Error(`Target directory already exists: ${targetRoot}`);
    }
  
    fs.mkdirSync(targetRoot, { recursive: true });
  
    // Create frontend and backend directories
    const frontendDir = path.join(targetRoot, 'frontend');
    const backendDir = path.join(targetRoot, 'backend');
    fs.mkdirSync(frontendDir, { recursive: true });
    fs.mkdirSync(backendDir, { recursive: true });
  
    // Optional: add .gitkeep so empty dirs are visible in git
    fs.writeFileSync(path.join(frontendDir, '.gitkeep'), '', 'utf8');
    fs.writeFileSync(path.join(backendDir, '.gitkeep'), '', 'utf8');
  
    const readmeContent = `# ${projectName}
  
  Generated by StackSpark-CLI.
  
  Stack:
  - template: ${stack.template}
  - frontend: ${stack.frontend}
  - backend: ${stack.backend}
  - database: ${stack.database}
  - saas: ${stack.saas ? 'enabled' : 'disabled'}
  
  Structure (MVP):
  - frontend/
  - backend/
  `;
  
    fs.writeFileSync(path.join(targetRoot, 'README.md'), readmeContent, 'utf8');
  
    console.log(`\nProject directory created at: ${targetRoot}`);
    console.log('Currently contains:');
    console.log('- README.md');
    console.log('- frontend/');
    console.log('- backend/');
  }